package com.huyy.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.9
 * 2019-05-30T16:04:51.754+08:00
 * Generated source version: 3.2.9
 *
 */
@WebServiceClient(name = "StudentScoreServiceService",
                  wsdlLocation = "http://localhost:8089/score?wsdl",
                  targetNamespace = "http://service.huyy.com/")
public class StudentScoreServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.huyy.com/", "StudentScoreServiceService");
    public final static QName StudentScoreServicePort = new QName("http://service.huyy.com/", "StudentScoreServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8089/score?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(StudentScoreServiceService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8089/score?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public StudentScoreServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public StudentScoreServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StudentScoreServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public StudentScoreServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public StudentScoreServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public StudentScoreServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns StudentScoreService
     */
    @WebEndpoint(name = "StudentScoreServicePort")
    public StudentScoreService getStudentScoreServicePort() {
        return super.getPort(StudentScoreServicePort, StudentScoreService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StudentScoreService
     */
    @WebEndpoint(name = "StudentScoreServicePort")
    public StudentScoreService getStudentScoreServicePort(WebServiceFeature... features) {
        return super.getPort(StudentScoreServicePort, StudentScoreService.class, features);
    }

}
