package com.huyy.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.9
 * 2019-05-30T16:04:51.707+08:00
 * Generated source version: 3.2.9
 *
 */
@WebService(targetNamespace = "http://service.huyy.com/", name = "StudentScoreService")
@XmlSeeAlso({ObjectFactory.class})
public interface StudentScoreService {

    @WebMethod
    @RequestWrapper(localName = "getScore", targetNamespace = "http://service.huyy.com/", className = "com.huyy.client.GetScore")
    @ResponseWrapper(localName = "getScoreResponse", targetNamespace = "http://service.huyy.com/", className = "com.huyy.client.GetScoreResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int getScore(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
